# -*- coding: utf-8 -*-
"""bpsk_awgn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jw6pKMT1X218TUJ16SmLWvypNO9rPrCQ
"""

# Commented out IPython magic to ensure Python compatibility.
import os # Configure which GPU
if os.getenv("CUDA_VISIBLE_DEVICES") is None:
    gpu_num = 0 # Use "" to use the CPU
    os.environ["CUDA_VISIBLE_DEVICES"] = f"{gpu_num}"

# Import Sionna
try:
    import sionna.phy
except ImportError as e:
    import sys
    if 'google.colab' in sys.modules:
       # Install Sionna in Google Colab
       print("Installing Sionna and restarting the runtime. Please run the cell again.")
       os.system("pip install sionna")
       os.kill(os.getpid(), 5)
    else:
       raise e

# Import PyTorch
import torch

import numpy as np

# For plotting
# %matplotlib inline

import matplotlib.pyplot as plt

# for performance measurements
import time

# Model
class UncodedSystemAWGN(sionna.phy.Block):
    def __init__(self, num_bits_per_symbol, block_length):
        super().__init__()
        self.num_bits_per_symbol = num_bits_per_symbol
        self.block_length        = block_length
        self.constellation = sionna.phy.mapping.Constellation("pam", self.num_bits_per_symbol) #using 2-PAM as BPSK
        self.mapper        = sionna.phy.mapping.Mapper(constellation=self.constellation)
        self.demapper      = sionna.phy.mapping.Demapper("app", constellation=self.constellation)
        self.binary_source = sionna.phy.mapping.BinarySource()
        self.awgn_channel  = sionna.phy.channel.AWGN()

    def call(self, batch_size, ebno_db):
        no   = sionna.phy.utils.ebnodb2no(ebno_db,
                                           num_bits_per_symbol=self.num_bits_per_symbol,
                                           coderate=1.0)
        bits = self.binary_source([batch_size, self.block_length])
        x    = self.mapper(bits)
        y    = self.awgn_channel(x, no)
        llr  = self.demapper(y, no)
        return bits, llr

# Simulation parameters
NUM_BITS_PER_SYMBOL = 1
BLOCK_LENGTH        = 1024
BATCH_SIZE          = 2000
EBN0_DB_MIN         = -3.0
EBN0_DB_MAX         = 5.0

model = UncodedSystemAWGN(
    num_bits_per_symbol=NUM_BITS_PER_SYMBOL,
    block_length=BLOCK_LENGTH
)

# ── Monte Carlo Sim via Sionna
ber_plots = sionna.phy.utils.PlotBER("2-PAM / BPSK over AWGN")
ber_plots.simulate(
    model,
    ebno_dbs=np.linspace(EBN0_DB_MIN, EBN0_DB_MAX, 20),
    batch_size=BATCH_SIZE,
    num_target_block_errors=100,
    legend="2-PAM Monte Carlo",
    soft_estimates=True,
    max_mc_iter=100,
    show_fig=False          # suppressing Sionna's own figure
)

#print(dir(ber_plots))  This gave the attributes that PlotBER stores, using the _snrs and _bers from it.
mc_snrs = ber_plots._snrs[0]   # Eb/N0 values for first (only) curve
mc_bers = ber_plots._bers[0]   # BER values for first (only) curve

# Theoretical BPSK BER
def qfunc(x):
    return 0.5 * erfc(x / np.sqrt(2.0))

ebno_dbs_theory = np.linspace(EBN0_DB_MIN, EBN0_DB_MAX, 100)
ebno_linear     = 10 ** (ebno_dbs_theory / 10.0)
ber_theory      = qfunc(np.sqrt(2 * ebno_linear))

# Plot
fig, ax = plt.subplots(figsize=(8, 5))

ax.semilogy(mc_snrs, mc_bers, 'bo-',
            linewidth=2, markersize=5, label="2-PAM Monte Carlo")
ax.semilogy(ebno_dbs_theory, ber_theory, 'r--',
            linewidth=2, label="BPSK Theoretical")

ax.set_xlabel("Eb/N0 (dB)", fontsize=12)
ax.set_ylabel("BER", fontsize=12)
ax.set_title("2-PAM / BPSK over AWGN", fontsize=13)
ax.legend(fontsize=11)
ax.grid(True, which="both")
ax.set_ylim([1e-5, 1])
ax.set_xlim([EBN0_DB_MIN, EBN0_DB_MAX])

plt.tight_layout()
plt.show()
